server:
  port: 8099

spring:
  application:
    name: ms-products

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: http://${eureka.instance.hostname}:${server.port}/eureka